services:
  zero:
    build: .
    expose:
      - "5000"
      - "9090"
    ports:
      - "5000:5000"
      - "9090:9090"
    environment:
      - "ENV=PROD"
    # links:
    #   - "dnmonster"
    #   - "redis"
    networks:
      - bridge
  
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - bridge

  redis:
    image: redis:3.0
    networks:
      - bridge

networks:
  bridge:
    name: bridge
    external: true
