services:
  zero:
    build: .
    expose:
      - "5000"
      - "9090"
    ports:
      - "5000:5000"
      - "9090:9090"
    environment:
      - "ENV=PROD"
    # links:
    #   - "dnmonster"
    #   - "redis"
    networks:
      - prod-net
  
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - prod-net

  redis:
    image: redis:3.0
    networks:
      - prod-net

networks:
  prod-net:
    driver: bridge
    name: prod-net
    external: true
